-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 10:24:47 2023
-- Model: New Model    Version: 1.060
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_covidLonga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_covidLonga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_covidLonga` DEFAULT CHARACTER SET utf8 ;
USE `mydb_covidLonga` ;



-- -----------------------------------------------------
-- Table `mydb_covidLonga`.`coviLonga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_covidLonga`.`coviLonga` (
  `idcovidLonga` INT NOT NULL AUTO_INCREMENT,
  `covid` VARCHAR(45) NOT NULL,
  `probabilidade` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idcovidLonga`),
  UNIQUE INDEX `idcovidLonga_UNIQUE` (`idcovidLonga` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_covidLonga`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_covidLonga`.`admin` (
  `idadmin` INT NOT NULL,
  `numero_adm` INT NOT NULL AUTO_INCREMENT,
  `nome_admin` VARCHAR(50) NOT NULL,
  `admincol` VARCHAR(45) NULL,
  `coviLonga_idcovidLonga` INT NOT NULL,
  PRIMARY KEY (`idadmin`),
  UNIQUE INDEX `idadmin_UNIQUE` (`idadmin` ASC) VISIBLE,
  UNIQUE INDEX `nome_admin_UNIQUE` (`nome_admin` ASC) VISIBLE,
  UNIQUE INDEX `numero_adm_UNIQUE` (`numero_adm` ASC) VISIBLE,
  INDEX `fk_admin_coviLonga1_idx` (`coviLonga_idcovidLonga` ASC) VISIBLE,
  CONSTRAINT `fk_admin_coviLonga1`
    FOREIGN KEY (`coviLonga_idcovidLonga`)
    REFERENCES `mydb_covidLonga`.`coviLonga` (`idcovidLonga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_covidLonga`.`questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_covidLonga`.`questionario` (
  `idquestionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idade` INT NOT NULL,
  `sexo` VARCHAR(45) NULL,
  `raca` VARCHAR(50) NOT NULL,
  `doenca` VARCHAR(50) NOT NULL,
  `covid_Data` DATETIME NOT NULL,
  `ocupacao_hospitalar` VARCHAR(10) NOT NULL,
  `periodo` INT UNSIGNED NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`idquestionario`),
  UNIQUE INDEX `idquestionario_UNIQUE` (`idquestionario` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `covid_Data_UNIQUE` (`covid_Data` ASC) VISIBLE,
  INDEX `fk_questionario_admin1_idx` (`admin_idadmin` ASC) VISIBLE,
  CONSTRAINT `fk_questionario_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `mydb_covidLonga`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_covidLonga`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_covidLonga`.`usuario` (
  `idnome` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `usuariocol` VARCHAR(20) NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL,
  `questionario_idquestionario` INT NOT NULL,
  `covidLonga_idcovidLonga` INT NOT NULL,
  PRIMARY KEY (`idnome`),
  UNIQUE INDEX `nome_UNIQUE` (`idnome` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_usuario_questionario1_idx` (`questionario_idquestionario` ASC) VISIBLE,
  INDEX `fk_usuario_covidLonga1_idx` (`covidLonga_idcovidLonga` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_questionario1`
    FOREIGN KEY (`questionario_idquestionario`)
    REFERENCES `mydb_covidLonga`.`questionario` (`idquestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_covidLonga1`
    FOREIGN KEY (`covidLonga_idcovidLonga`)
    REFERENCES `mydb_covidLonga`.`coviLonga` (`idcovidLonga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_covidLonga`.`login_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_covidLonga`.`login_admin` (
  `idLOGIN_ADMIM` INT NOT NULL AUTO_INCREMENT,
  `-NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `usuario_idnome` VARCHAR(50) NOT NULL,
  INDEX `fk_login_admin_usuario_idx` (`usuario_idnome` ASC) VISIBLE,
  CONSTRAINT `fk_login_admin_usuario`
    FOREIGN KEY (`usuario_idnome`)
    REFERENCES `mydb_covidLonga`.`usuario` (`idnome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_covidLonga`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_covidLonga`.`sintomas` (
  `idsintomas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fadiga` VARCHAR(45) NOT NULL,
  `dispneia` VARCHAR(45) NOT NULL,
  `olfato` VARCHAR(45) NOT NULL,
  `paladar` VARCHAR(45) NOT NULL,
  `depressao` VARCHAR(45) NOT NULL,
  `ansiedade` VARCHAR(45) NOT NULL,
  `Febre` VARCHAR(45) NOT NULL,
  `Tosse` VARCHAR(45) NOT NULL,
  `respiratorio` VARCHAR(45) NOT NULL,
  `Diarreia` VARCHAR(45) NOT NULL,
  `cardíacas` VARCHAR(45) NOT NULL,
  `insonia` VARCHAR(45) NOT NULL,
  `questionario_idquestionario` INT NOT NULL,
  PRIMARY KEY (`idsintomas`),
  INDEX `fk_sintomas_questionario1_idx` (`questionario_idquestionario` ASC) VISIBLE,
  CONSTRAINT `fk_sintomas_questionario1`
    FOREIGN KEY (`questionario_idquestionario`)
    REFERENCES `mydb_covidLonga`.`questionario` (`idquestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
